tasks:
  - init: npm install && pip install crc8
    command: |
      gp await-port 8000
      dfx build
      dfx canister install --all
      ID=$(xxd -u -p canisters/nnsexplorer/_canister.id)
      CRC=$(python2 -c "import crc8;h=crc8.crc8();h.update('$ID'.decode('hex'));print(h.hexdigest().upper())")
      gp preview $(gp url 8000)/?canisterId=ic:$ID$CRC
  - command: dfx start
    name: replica
    openMode: tab-after
image:
  file: .gitpod.Dockerfile
ports:
  - port: 8000
    onOpen: ignore
vscode:
  extensions:
    - dfinity-foundation.vscode-motoko@0.3.4:94sM6KNSH0sWMuF40BrlUQ==
